# Generated by Django 5.2.6 on 2025-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('po_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_department', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Sent', 'Sent')], default='Draft', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=10)),
                ('po_reference_document', models.FileField(blank=True, null=True, upload_to='po_references/')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_email', models.EmailField(max_length=254)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('item_no', models.CharField(max_length=50)),
                ('item_description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('item_currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=10)),
                ('delivery_date_expected', models.DateField()),
                ('delivery_address', models.TextField()),
                ('inco_terms', models.CharField(blank=True, choices=[('FOB', 'FOB'), ('CIF', 'CIF'), ('EXW', 'EXW')], max_length=20, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('Courier', 'Courier'), ('Freight', 'Freight'), ('Air', 'Air'), ('Sea', 'Sea')], max_length=50, null=True)),
                ('payment_terms', models.CharField(max_length=50)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('approved_by', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='po_attachments/')),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('supplier_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(max_length=100)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_number', models.CharField(max_length=50, unique=True)),
                ('pr_date', models.DateField()),
                ('requested_by', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('item_description', models.TextField()),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('uom', models.CharField(max_length=20)),
                ('estimated_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=10)),
                ('preferred_supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('budget_code', models.CharField(max_length=50)),
                ('justification', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('approver', models.CharField(max_length=100)),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
